---
title: "Figure_S6"
author: "David Bradley"
date: '2023-07-14'
output: html_document
---

# GGplot font

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```

# Generate a simple bar plot for EPHB3

```{r}

master_files <- list.files() # Go to the directory containing all of the 'master' files for each kinase
master_files <- master_files[grep('-EPHB3_',master_files)] # Retrieve the file corresponding to EPHB3

master_foldx_gemme_log2_all <- NULL 

for (i in 1:length(master_files)) {
  
  print(i)
  
  master_file <- read.csv(master_files[i])
  master_foldx_gemme_log2 <- master_file[,c(1:17,36)] # Retrieve all of the relevant columns
  
  master_foldx_gemme_log2_all <- rbind(master_foldx_gemme_log2_all,master_foldx_gemme_log2)
  
}

# Unique_sites only

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all[!duplicated(master_foldx_gemme_log2_all[c(5,6)]),]

# exclude proteins with no AF2

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,17] %in% 'no AF2',]

# total number of upregulated pY for this kinase
ephb3_total_pY <- nrow(master_foldx_gemme_log2_all_unique)

# exclude proteins where there were too few homologues to perform GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] %in% 'na',]

# exclude proteins where the MSA was too problematic for GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] == 'NaN',]

## ddG (intra), ddE (norm), RSA

ddG_ddE_log2 <- master_foldx_gemme_log2_all_unique[,c(17,16,11)]
ddG_ddE_log2[,1] <- as.numeric(ddG_ddE_log2[,1])
ddG_ddE_log2[,2] <- as.numeric(ddG_ddE_log2[,2])
ddG_ddE_log2[,3] <- as.numeric(ddG_ddE_log2[,3])

# Ennumerate the different phosphorylation categories

ephb3_total_pY <- nrow(master_foldx_gemme_log2_all_unique)
ephb3_ddG <- length(which(ddG_ddE_log2[,1] >=2))
ephb3_ddE <- length(which(ddG_ddE_log2[,2] >= 0.8))

## gg barplot

col1 <- c('all pY','ddG > 2','ddE > 0.8')  
col2 <- c(ephb3_total_pY, ephb3_ddG, ephb3_ddE)

sim_df <- data.frame(col1,col2)
colnames(sim_df) <- c('class','fraction')

sim_df$class <- factor(sim_df$class, levels = c(c('all pY','ddG > 2','ddE > 0.8')))

p <- ggplot(sim_df, aes(x=class, y=fraction, fill=class, width=.6)) + geom_bar(color=NA, lwd=0, stat='identity', alpha=0.55) + scale_fill_manual(values = c(rgb(53/255,183/255,121/255,128/255),rgb(53/255,183/255,121/255,128/255),rgb(53/255,183/255,121/255,128/255)))

# Font
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))+theme(legend.position="none")

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")))
p <- p + ylab("") + xlab("") + ggtitle('EPHB3')
p <- p+theme(axis.text.x=element_text(size=10, face='bold'),axis.text.y=element_text(size=10),axis.title.x=element_text(size=11,face="plain"),axis.title.y=element_text(size=8,face="plain",vjust=-10),plot.title=element_text(size=11.5,face='bold'))
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p + theme(panel.border = element_blank())

ephb3_sim_df <- sim_df

```

# Generate a simple bar plot for EPHB1

```{r}

master_files <- list.files() # Go to the directory containing all of the 'master' files for each kinase
master_files <- master_files[grep('-EPHB1_',master_files)] # Retrieve the file corresponding to EPHB3

master_foldx_gemme_log2_all <- NULL 

for (i in 1:length(master_files)) {
  
  print(i)
  
  master_file <- read.csv(master_files[i])
  master_foldx_gemme_log2 <- master_file[,c(1:17,36)] # Retrieve the relevant columns
  
  master_foldx_gemme_log2_all <- rbind(master_foldx_gemme_log2_all,master_foldx_gemme_log2)
  
}

# Unique_sites only

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all[!duplicated(master_foldx_gemme_log2_all[c(5,6)]),]

# exclude proteins with no AF2

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,17] %in% 'no AF2',]

# total number of upregulated pY for this kinase
ephb3_total_pY <- nrow(master_foldx_gemme_log2_all_unique)

# exclude proteins where there were too few homologues to perform GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] %in% 'na',]

# exclude proteins where the MSA was too problematic for GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] == 'NaN',]

## ddG (intra), ddE (norm), RSA

ddG_ddE_log2 <- master_foldx_gemme_log2_all_unique[,c(17,16,11)]
ddG_ddE_log2[,1] <- as.numeric(ddG_ddE_log2[,1])
ddG_ddE_log2[,2] <- as.numeric(ddG_ddE_log2[,2])
ddG_ddE_log2[,3] <- as.numeric(ddG_ddE_log2[,3])

# Enumerate the different phosphorylations

ephb1_total_pY <- nrow(master_foldx_gemme_log2_all_unique)
ephb1_ddG <- length(which(ddG_ddE_log2[,1] >=2))
ephb1_ddE <- length(which(ddG_ddE_log2[,2] >= 0.8))

## gg barplot

col1 <- c('all pY','ddG > 2','ddE > 0.8')  
col2 <- c(ephb1_total_pY, ephb1_ddG, ephb1_ddE)

sim_df <- data.frame(col1,col2)
colnames(sim_df) <- c('class','fraction')

sim_df$class <- factor(sim_df$class, levels = c(c('all pY','ddG > 2','ddE > 0.8')))

p <- ggplot(sim_df, aes(x=class, y=fraction, fill=class, width=.6)) + geom_bar(color=NA, lwd=0, stat='identity', alpha=0.55) + scale_fill_manual(values = c(rgb(53/255,183/255,121/255,128/255),rgb(53/255,183/255,121/255,128/255),rgb(53/255,183/255,121/255,128/255)))

# Font
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))+theme(legend.position="none")

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")))
p <- p + ylab("") + xlab("") + ggtitle('EPHB3')
p <- p+theme(axis.text.x=element_text(size=10, face='bold'),axis.text.y=element_text(size=10),axis.title.x=element_text(size=11,face="plain"),axis.title.y=element_text(size=8,face="plain",vjust=-10),plot.title=element_text(size=11.5,face='bold'))
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p + theme(panel.border = element_blank())

ephb1_sim_df <- sim_df

```

# Generate a simple bar plot for vSRC

```{r}

master_files <- list.files() # Go to the directory containing all of the 'master' files for each kinas
master_files <- master_files[grep('pY-vSRC_',master_files)] # Retrieve the file corresponding to vSRC

master_foldx_gemme_log2_all <- NULL 

for (i in 1:length(master_files)) {
  
  print(i)
  
  master_file <- read.csv(master_files[i])
  master_foldx_gemme_log2 <- master_file[,c(1:17,36)] # Retrieve the relevant columns
  
  master_foldx_gemme_log2_all <- rbind(master_foldx_gemme_log2_all,master_foldx_gemme_log2)
  
}

# Unique_sites only

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all[!duplicated(master_foldx_gemme_log2_all[c(5,6)]),]

# exclude proteins with no AF2

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,17] %in% 'no AF2',]

# total number of upregulated pY for this protein

vsrc_total_pY <- nrow(master_foldx_gemme_log2_all_unique)

# exclude proteins where there were too few homologues to perform GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] %in% 'na',]

# exclude proteins where the MSA was too problematic for GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] == 'NaN',]

## ddG (intra), ddE (norm), RSA

ddG_ddE_log2 <- master_foldx_gemme_log2_all_unique[,c(17,16,11)]
ddG_ddE_log2[,1] <- as.numeric(ddG_ddE_log2[,1])
ddG_ddE_log2[,2] <- as.numeric(ddG_ddE_log2[,2])
ddG_ddE_log2[,3] <- as.numeric(ddG_ddE_log2[,3])

# Enumerate the different phosphorylations

vsrc_total_pY <- nrow(master_foldx_gemme_log2_all_unique)
vsrc_ddG <- length(which(ddG_ddE_log2[,1] >=2))
vsrc_ddE <- length(which(ddG_ddE_log2[,2] >= 0.8))

## gg barplot

col1 <- c('all pY','ddG > 2','ddE > 0.8')  
col2 <- c(vsrc_total_pY, vsrc_ddG, vsrc_ddE)

sim_df <- data.frame(col1,col2)
colnames(sim_df) <- c('class','fraction')

sim_df$class <- factor(sim_df$class, levels = c(c('all pY','ddG > 2','ddE > 0.8')))

p <- ggplot(sim_df, aes(x=class, y=fraction, fill=class, width=.6)) + geom_bar(color=NA, lwd=0, stat='identity', alpha=0.55) + scale_fill_manual(values = c(rgb(53/255,183/255,121/255,128/255),rgb(53/255,183/255,121/255,128/255),rgb(53/255,183/255,121/255,128/255)))

# Font
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))+theme(legend.position="none")

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")))
p <- p + ylab("") + xlab("") + ggtitle('EPHB3')
p <- p+theme(axis.text.x=element_text(size=10, face='bold'),axis.text.y=element_text(size=10),axis.title.x=element_text(size=11,face="plain"),axis.title.y=element_text(size=8,face="plain",vjust=-10),plot.title=element_text(size=11.5,face='bold'))
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p + theme(panel.border = element_blank())

vsrc_sim_df <- sim_df

```

# Multi-faceted plot

```{r}

ephb3_ephb1_vsrc_sim_df <- rbind(ephb3_sim_df,ephb1_sim_df,vsrc_sim_df)
ephb3_ephb1_vsrc_sim_df$kinase <- c(rep('EPHB3',3),rep('EPHB1',3),rep('vSRC',3))
ephb3_ephb1_vsrc_sim_df$kinase  <- factor(ephb3_ephb1_vsrc_sim_df$kinase , levels = c(c('EPHB3','vSRC','EPHB1')))

# Tidy up the names

p <- ggplot(ephb3_ephb1_vsrc_sim_df, aes(x=class, y=fraction, fill=class, width=.6)) + geom_bar(color=NA, lwd=0, stat='identity', alpha=0.55) + scale_fill_manual(values = c(colors()[155],colors()[155],colors()[155]))
p <- p+ scale_x_discrete(labels= c(expression(bold('all pY')),c(expression(bold(Delta*Delta*'G >2'))),c(expression(bold(Delta*Delta*'E >0.8')))))
p <- p + facet_wrap(vars(kinase), nrow = 1)
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="bold", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))+theme(legend.position="none")

# Ticks
p <- p + ylab("No. of upregulated pY") + xlab("") + ggtitle('')
p <- p+theme(axis.text.x=element_text(size=11, face='bold'),axis.text.y=element_text(size=10),axis.title.x=element_text(size=11,face="bold"),axis.title.y=element_text(size=15,face="bold",vjust=1),plot.title=element_text(size=11.5,face='bold'))
p <- p + theme(axis.text.x = element_text(angle = 45, vjust = 0.4, hjust=0.4))
p <- p+theme(plot.title = element_text(hjust = 0.5))

ggsave(file='Figure_S6.pdf', plot=p, width=4.075, height=5.0)

```


