---
title: "Figure_3g"
author: "David Bradley"
date: '2023-07-14'
output: html_document
---

# GGplot font

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```

# Weighted ddE values

```{r}

master_files <- list.files('/home/david/Documents/Work/HFSP_hhblits_GEMME/GEMME_master_files_weighted/',full.names =T) # Go to the directory containing all of the kinase master files with the weighted ddE values 

master_foldx_gemme_log2_all <- NULL 

for (i in 1:length(master_files)) {
  
  print(i)
  
  master_file <- read.csv(master_files[i])
  master_foldx_gemme_log2 <- master_file[,c(1:17,36)]
  
  master_foldx_gemme_log2_all <- rbind(master_foldx_gemme_log2_all,master_foldx_gemme_log2)
  
}

# unique_sites only
master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all[!duplicated(master_foldx_gemme_log2_all[c(5,6)]),]

# exclude proteins with no AF2 models

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,17] %in% 'no AF2',]

# exclude proteins where there were too few homologues to perform GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] %in% 'na',]

# exclude proteins where the MSA was too problematic for GEMME

master_foldx_gemme_log2_all_unique <- master_foldx_gemme_log2_all_unique[!master_foldx_gemme_log2_all_unique[,16] == 'NaN',]

## ddG (intra), ddE (weighted), RSA

ddG_ddE_rsa <- master_foldx_gemme_log2_all_unique[,c(17,16,11)]
ddG_ddE_rsa[,1] <- as.numeric(ddG_ddE_rsa[,1])
ddG_ddE_rsa[,2] <- as.numeric(ddG_ddE_rsa[,2])
ddG_ddE_rsa[,3] <- as.numeric(ddG_ddE_rsa[,3])

weighted_ddG_ddE_rsa <- ddG_ddE_rsa

```

# ggplot

```{r}

library(viridis)
library(RColorBrewer)

p <- ggplot(ddG_ddE_rsa, aes(x=ddG_intra, y=ddE_norm, color=RSA)) + geom_point(size=1.3)
p <- p+scale_color_gradient(low='#6baed6', high='#3f007d')
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_blank())
p <- p+theme(axis.text=element_text(size=11),axis.title.x=element_text(size=14,face="bold"),axis.title.y=element_text(size=14,face="bold"),plot.title=element_text(size=18,face='bold'))
p <- p + ylab(c(expression(bold(Delta*Delta*'E (conservation)')))) + xlab(c(expression(bold(Delta*Delta*'G (structure)')))) + ggtitle('')
p <- p + labs(colour = "RSA") 
p <- p + theme(legend.key.size = unit(0.5, 'cm'), #change legend key size
        legend.key.height = unit(0.5, 'cm'), #change legend key height
        legend.key.width = unit(0.5, 'cm'), #change legend key width
        legend.title = element_text(size=11), #change legend title font size
        legend.text = element_text(size=9)) #change legend text font size

ggsave(file='Figure_3g.pdf', plot=p, width=6.25, height=4.0)

```




