---
title: "Figue_S5"
author: "David Bradley"
date: '2023-07-14'
output: html_document
---

# GGplot font

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```

# Weighted ddE values

```{r}

library(viridis)

master_files <- list.files('',full.names=T) # Go to the directory containing all of the kinase master files with the weighted ddE values 

# As opposed to the main figure panel, this time we want to generate the ddG vs. ddE plot per kinase

for (i in 1:length(master_files)) {
  
  print(i)
  
  master_file <- read.csv(master_files[i])
  master_foldx_gemme_log2 <- master_file[,c(1:17,36)]
  
  # parse the kinase name and kinase group from the file names 
  
  kin_path <- rapply(strsplit(master_files[i],split='-'), function(x) x[1])
  kin_file <- rapply(strsplit(master_files[i],split='-'), function(x) x[2])
  
  kin_nom <- rapply(strsplit(kin_file,split='_'), function(x) x[1])
  kin_group <- rapply(strsplit(kin_path,split='/'), function(x) x[length(x)])  
  
  # Make adjustments for IRAK4 and TLK2 because the format of the file name is slightly different.
  
  if (kin_group == 'IRAK4_master_GEMME.csv') {
    kin_group <- 'pST'
    kin_nom <- 'IRAK4'
  }
  
  if (kin_group == 'TLK2_master_GEMME.csv') {
    kin_group <- 'pST'
    kin_nom <- 'TLK2'
  }
  
  # unique_sites only
  master_foldx_gemme_log2_unique <- master_foldx_gemme_log2[!duplicated(master_foldx_gemme_log2[c(5,6)]),]
  
  # require for there to be at least 100 upregulated psites for me to generate a plot
  if(nrow(master_foldx_gemme_log2_unique) < 75) {next}
  
  ## exclude proteins with no AF2 models
  master_foldx_gemme_log2_unique <- master_foldx_gemme_log2_unique[!master_foldx_gemme_log2_unique[,17] %in% 'no AF2',]
  
  # exclude proteins where there were too few homologues to perform GEMME
  master_foldx_gemme_log2_unique <- master_foldx_gemme_log2_unique[!master_foldx_gemme_log2_unique[,16] %in% 'na',]
  
  # exclude proteins where the MSA was too problematic for GEMME
  master_foldx_gemme_log2_unique <- master_foldx_gemme_log2_unique[!master_foldx_gemme_log2_unique[,16] == 'NaN',]
  master_foldx_gemme_log2_unique <- master_foldx_gemme_log2_unique[!is.na(master_foldx_gemme_log2_unique[,16]),]
  
  ## ddG (intra), ddE (weighted), RSA

  ddG_ddE_rsa <- master_foldx_gemme_log2_unique[,c(17,16,11)]
  ddG_ddE_rsa[,1] <- as.numeric(ddG_ddE_rsa[,1])
  ddG_ddE_rsa[,2] <- as.numeric(ddG_ddE_rsa[,2])
  ddG_ddE_rsa[,3] <- as.numeric(ddG_ddE_rsa[,3])

  weighted_ddG_ddE_rsa <- ddG_ddE_rsa
  
  # sample size of deleterious pY
  
  struc_del <- nrow(ddG_ddE_rsa[ddG_ddE_rsa[,1] > 2,])
  cons_del <- nrow(ddG_ddE_rsa[ddG_ddE_rsa[,2] > 0.8,])
  unique_del <- length(unique(c(which(ddG_ddE_rsa[,1] > 2),which(ddG_ddE_rsa[,2] > 0.8))))
  
  # set the color based upon the class of the kinase
  
  mycol <- NULL
  
  if(kin_group == 'pY') {mycol <- rgb(49/255,104/255,142/255,128/255)} # blue
  if(kin_group == 'pYd') {mycol <- rgb(53/255,183/255,121/255,128/255)} # green
  if(kin_group == 'vSRC') {mycol <- rgb(253/255,231/255,37/255,128/255)} # yellow
  if(kin_group == 'pST') {mycol <- rgb(147/255,112/255,219/255,128/255)} # purple
  
  ## ggplot
  
  p <- ggplot(ddG_ddE_rsa, aes(x=ddG_intra, y=ddE_norm, color=RSA)) + geom_point(size=1.3)
  p <- p+scale_color_gradient(low=mycol, high=mycol)
  p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))
  p <- p+theme(axis.text=element_text(size=11),axis.title.x=element_text(size=14,face="bold"),axis.title.y=element_text(size=14,face="bold"),plot.title=element_text(size=15,face='bold'))
  p <- p + ylab('') + xlab('') + ggtitle(kin_nom)
  p <- p + labs(colour = "RSA") 
  p <- p+ theme(plot.title = element_text(hjust = 0.5))
  p <- p+coord_cartesian(xlim=c(0,35),y=c(0,1))
  p <- p + theme(panel.border = element_blank())
  p <- p + theme(legend.key.size = unit(0.5, 'cm'), #change legend key size
          legend.key.height = unit(0.5, 'cm'), #change legend key height
          legend.key.width = unit(0.5, 'cm'), #change legend key width
          legend.title = element_text(size=11), #change legend title font size
          legend.text = element_text(size=9)) #change legend text font size
  
  # Remove legend
  p <- p + theme(legend.position = "none") 
  
  # Text detailing the number of deleterious pY for this kinase
  
  struc_com <- paste(struc_del,'destabilising pY')
  cons_com <-  paste(cons_del,'conserved Y')
  unique_com <- paste(unique_del,'unique deleterious pY')
  
  # Slight modification to text if we are dealing with one of the two active S/T kinases
  
  if (kin_nom %in% c('IRAK4','TLK2')) {
      struc_com <- paste(struc_del,'destabilising pST')
      cons_com <-  paste(cons_del,'conserved S/T')
      unique_com <- paste(unique_del,'unique deleterious pST')
  }
  
  # split text (so that we can independently modify the fontface and text size)
  
  struc_com1 <- paste(strsplit(struc_com,' ')[[1]][1])
  struc_com2 <- paste(strsplit(struc_com,' ')[[1]][c(2,3)],collapse=' ')
  
  cons_com1 <- paste(strsplit(cons_com,' ')[[1]][1])
  cons_com2 <- paste(strsplit(cons_com,' ')[[1]][c(2,3)],collapse=' ')
  
  unique_com1 <- paste(strsplit(unique_com,' ')[[1]][1])
  unique_com2 <- paste(strsplit(unique_com,' ')[[1]][c(2,3,4)],collapse=' ')
  
  # Add text
  
  p <- p+geom_text(label=struc_com1,x=13, y=0.25, inherit.aes = F, check_overlap = T, size=3.3, hjust=0, fontface='bold')
  p <- p+geom_text(label=cons_com1,x=13, y=0.175, inherit.aes = F, check_overlap = T, size=3.3, hjust=0, fontface='bold')
  p <- p+geom_text(label=unique_com1,x=13, y=0.10, inherit.aes = F, check_overlap = T, size=3.3, hjust=0, fontface='bold')
  
  p <- p+geom_text(label=struc_com2,x=17.1, y=0.25, inherit.aes = F, check_overlap = T, size=2.95, hjust=0, fontface='plain')
  p <- p+geom_text(label=cons_com2,x=17.1, y=0.175, inherit.aes = F, check_overlap = T, size=2.95, hjust=0, fontface='plain')
  p <- p+geom_text(label=unique_com2,x=17.1, y=0.10, inherit.aes = F, check_overlap = T, size=2.95, hjust=0, fontface='plain')
  
  # assign this plot to an object name
  
  object_name <- paste('g',i,sep='')
  assign(object_name,p)
  
}

```

# Assemble panels in cowplot

```{r}

library(grid)
library(gridExtra)
library(cowplot)

g0 <- ggplot()+theme_bw()+theme(panel.border = element_blank()) # empty box

cowplot_row1 <- plot_grid(g2, g3, g4, g6, g7, g8, label_size = 10, nrow=1)
cowplot_row2 <- plot_grid(g9, g10, g16, g17, g18, g20, label_size = 10, nrow=1)
cowplot_row3 <- plot_grid(g22, g25, g26, g27, g28, g29, label_size = 10, nrow=1)
cowplot_row4 <- plot_grid(g30, g31, g32, g33, g34, g35, label_size = 10, nrow=1)
cowplot_row5 <- plot_grid(g36, g37, g38, g1, g24, g0, label_size = 10, nrow=1)

# assemble
cowplot_all <- plot_grid(cowplot_row1,cowplot_row2,cowplot_row3,cowplot_row4,cowplot_row5,nrow=5)

#create common x and y labels

y.grob <- textGrob(c(expression(bold(Delta*Delta*'E (conservation)'))), 
                   gp=gpar(fontface="bold", col="black", fontsize=22), rot=90)

x.grob <- textGrob(c(expression(bold(Delta*Delta*'G (structure)'))), 
                   gp=gpar(fontface="bold", col="black", fontsize=22))

#add to plot

cowplot_all_labels <- grid.arrange(arrangeGrob(cowplot_all, left = y.grob, bottom = x.grob))

ggsave(file='Figure_S5.pdf', plot=grid.arrange(arrangeGrob(cowplot_all, left = y.grob, bottom = x.grob)), width=20, height=15)

```




