---
title: "Figure_2B"
output: html_document
---

# GGplot font

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```

# Retrieve the number of unique upregulated pY per kinase

```{r}

library(tidyverse)

# read in list of kinase conditions (WT vs. dead), sorted in terms of the number of upregulated pY identified by mass spectrometry

Y_kinase_sorted <- read.table('Y_kinase_sorted.txt',sep='\t')
Y_kinase_sorted <- Y_kinase_sorted[,1]

```

# Plot RSA per kinase

```{r}

# Iterate through the 'master' files for each kinase and then use this to retrieve RSA data per pY and per kinase 

library(viridis)

setwd("~/Documents/Work/HFSP_2022")

# Construct data frame with the RSA values for each phosphosite and kinase

RSA_df_global <- NULL

for (i in 1:length(Y_kinase_sorted)) {
  
  print(i)
  
  Y_kinase <- Y_kinase_sorted[i]
  
  # Retrieve the kinase gene symbol
  Y_kinase_tag <- rapply(strsplit(Y_kinase_sorted[i], split=' '), function(x) x[1])
  
  master_file_path <- paste(Y_kinase_tag,'_master.csv',sep='')
  master_file <- read_csv(master_file_path)
  master_file <- data.frame(master_file,stringsAsFactors = F)
  
  # Unique pY phosphosites only
  master_file <- master_file[!duplicated(master_file[,1:6]),]
  
  # Retrieve the group to which the kinase belongs (pY, pYd, or vSRC)
  Y_kinase_group <- rapply(strsplit(Y_kinase_tag,split='-'), function(x) x[1])
  Y_kinase_tag <- rapply(strsplit(Y_kinase_tag,split='-'), function(x) x[2])
  
  master_file_RSA <- master_file$RSA
  RSA_df <- data.frame(rep(Y_kinase_group,nrow(master_file)),rep(Y_kinase_tag,nrow(master_file)),master_file_RSA, stringsAsFactors = FALSE)
  colnames(RSA_df) <- c('Group','Kinase','RSA')
  
  RSA_df_global <- rbind(RSA_df_global,RSA_df)
  
}

# Remove values for which no AF2 model was available

RSA_df_global <- RSA_df_global[!RSA_df_global[,3] == 'no AF2',]
RSA_df_global$RSA <- as.numeric(RSA_df_global$RSA)

# Sort the kinases in terms of the number of upregulated pY sites (i.e kinase activity)

kin_name_default <- names(table(RSA_df_global$Kinase))
kin_name_sorted <- rapply(strsplit(Y_kinase_sorted, split=' '), function(x) x[1])
kin_name_sorted <- rapply(strsplit(kin_name_sorted, split='-'), function(x) x[2])

RSA_df_global$Kinase <- factor(RSA_df_global$Kinase, levels = c('TNK1','FES','TEC','SYK','ABL2','BMX','ABL1','LCK','FYN',
                                                                'FRK','SRC','LYN','MET','FGFR3','EPHA1','EPHB4','EPHA3',
                                                                'MERTK','EPHB3','FGFR2','EPHB1','L452A','V394A','L317A',
                                                            'V292A','L393A','V383A','vSRC','L360A','L451A','V329A','L491A','L435A','L308A','V281A'))

# R function for the median + quartiles

median.quartile <- function(x){
  out <- quantile(x, probs = c(0.25,0.5,0.75))
  names(out) <- c("ymin","y","ymax")
  return(out) 
}

# Convert all RSAs > 1 to 1 (this is caused simply by Ys at protein termini). There are only 17 cases but I think they all correspond to the same phosphosite.

RSA_df_global[RSA_df_global[,3] >1,3] <- 1

```

# For context, retrieve RSA values for endogenous pS/pT sites

```{r}

# Read in table of RSA and disorder values for the pS/pT reference phosphoproteome (Table S2) from Leutert et al., 2022.

pSpT_rsa_disorder <- read.csv('Leutert_S2_pSpT_rsa_disorder.csv')

# Add RSA values from pS/pT to the exisiting data frame (with data from Y kinases)

pSpT_rsa <- pSpT_rsa_disorder[,7]
pSpT_rsa <- data.frame(rep('pST \n(native)',length(pSpT_rsa)),rep('pST \n(native)',length(pSpT_rsa)),pSpT_rsa)
colnames(pSpT_rsa) <- colnames(RSA_df_global)

RSA_df_global <- rbind(RSA_df_global,pSpT_rsa)

```

## ggplot

```{r}

# Give correct order for the groups

RSA_df_global$Group <- factor(RSA_df_global$Group, levels = c('pY', 'pYd', 'vSRC', 'pST \n(native)'))

# Generate the violin plot

p <- ggplot(RSA_df_global, aes(x=Group, y=RSA, fill = Group)) + geom_violin(color='black', lwd=1.00, scale='width', width=0.55) + scale_fill_manual(values = c(rgb(49/255,104/255,142/255,128/255),rgb(53/255,183/255,121/255,128/255), rgb(253/255,231/255,37/255,128/255), rgb(147/255,112/255,219/255,128/255)))

p <- p +stat_summary(
    fun.data = median.quartile, color = colors()[180], lwd=0.75, show.legend = F)

# Font
p <- p+theme_bw() + theme(text=element_text(face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")))

p <- p + ylab("RSA") + xlab("") + ggtitle('')
#p <- p + theme(axis.title.y = element_text(vjust=-1.5))
p <- p+theme(axis.text=element_text(size=10.5),axis.title.x=element_text(size=16,face="plain"),axis.title.y=element_text(size=16,face="plain"),plot.title=element_text(size=18,face='bold'))
p <- p+theme(plot.title = element_text(hjust = 0.5))
#p <- p + scale_y_continuous(labels=c('0','','','','1'))
#p <- p + theme(axis.ticks.y = element_line(color = c("black", NA, NA, NA,"black")))
#p <- p+theme(axis.title.y = element_text(vjust=-7))
p <- p + theme(axis.ticks.x = element_line(color = c(NA, NA, NA, NA)))
p <- p + theme(legend.position = "none",panel.border = element_blank()) # axis.line = element_blank(), )

# Threshold for accessibility is commonly posed between 15% and 25%

p <- p + geom_hline(yintercept=0.2, linetype="dashed", color = "red", lwd=0.7)

# Legend

p <- p+theme(legend.key.size = unit(0.5, 'cm'),legend.title = element_text(size=0), legend.text = element_text(size=8))

#p <- p + theme(plot.margin = unit(c(0,0,0.1,0), "cm")) # t, r, b, l
#p <- p + theme(axis.text.x = element_text(angle = 30, vjust = 1.0, hjust=1))

p <- p+geom_text(data=data.frame(), aes(x=c(1:4), y=rep(1.04,4)), label=c(unname(table(RSA_df_global[,1])))[1:4],col=colors()[190], fontface='plain', size=3.0, inherit.aes = FALSE)

ggsave(file='2B_RSA.pdf', plot=p, width=3.5, height=4.0)

```